[package]
edition = "2021"
name = "w3s"
version = "0.1.0"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dependencies]
blake3 = "1"
futures = "0.3"
reqwest = { version = "0.11", features = ["stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt"] }

# --- optional ---
rand = { version = "0.8", optional = true }

## encryption
aes-gcm = { version = "0.9", optional = true }
argon2 = { version = "0.4", optional = true }

## compression
zstd = { version = "0.11", optional = true }

[features]
compression = ["rand", "zstd"]
encryption = ["rand", "aes-gcm", "argon2"]
